//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sellers
    {
        public int SellerID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<int> InvoiceDetail_InvoiceDetailID { get; set; }
    
        public virtual InvoiceDetails InvoiceDetails { get; set; }
    }
}
